version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - static:/var/www/django-project/resources/static
      - media:/var/www/django-project/resources/media
    depends_on:
      - web

  web:
    restart: always
    container_name: web
    build:
      context: .
    depends_on:
      - db
    volumes:
      - static:/var/www/django-project/resources/static
      - media:/var/www/django-project/resources/media
    expose:
      - "8000"
    environment:
      DUMMY: "DUMMY"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "myproject_production" # set this
      POSTGRES_USER: "myproject" # set this
      POSTGRES_PASSWORD: "hellodarknessmyoldfriend" # set this
    ports:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - postgres_data_backup:/backups

volumes:
  postgres_data:
  postgres_data_backup:
  static:
  media:
